# Books Banned in Texas State Prisons

In [2]:
# step 1: import pandas
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

# the 'magic' or the percent symbol means it will look good visually

In [5]:
# step 2: import .csv file
data = pd.read_csv("data/banned_book_data_tx-list.csv")

# output the first few data points
data.head()

# note on sourcing: got this information through a request to the tdcj public information office, received 10/14/2022

,publication,author,date,unit_deny_reason,reason,"note_on_sourcing:_i_got_this_information_through_a_request_to_the_tdcj_public_information_office,_received_10/14/2022.",year,month,day,state_arc
0,...AND THEIR MEMORY WAS A BITTER TREE,"HOWARD, ROBERT",2016-08-19,PAGES 81 & 369 SEXUALLY EXPLICIT IMAGE,PGS 81 & 369 SEXUALLY EXPLICIT IMAGE,NaN,2016,8,19,tx
1,"(NON)CONFORM RUSSIAN AND SOVIET ART 1958-1995,","THIEMANN, BARBARA",2012-09-10,PAGE 422 PHOTO OF A NUDE CHILD,PG 422 NUDE CHILD,NaN,2012,9,10,tx
2,SCUSE ME WHILE I KISS THE SKY,"HENDERSON, DAVID",2019-07-17,PG 294 SEXUALLY EXPLICIT IMAGE,PG 294 SEXUALLY EXPLICIT IMAGE,NaN,2019,7,17,tx
3,SCUSE ME WHILE I KISS THE SKY,"HENDERSON, DAVID",2010-01-29,PAGE 310 CONTAINS SEXUALLY EXPLICIT IMAGES,PAGE 9 OF PHOTO INSERT CONTAINS SEXUALLY EXPLI...,NaN,2010,1,29,tx
4,A BLACK GAZE,"CAMPT, TINA",2021-09-08,"PAGES 28, 30, 35 SEXUALLY EXPLICIT IMAGES","PAGES 28, 30 & 35 CONTAIN SEXUALLY EXPLICIT IM...",NaN,2021,9,8,tx

## Inspect the Data

In [6]:
data.shape

(9396, 10)

In [7]:
data.columns

Index(['publication', 'author', 'date', 'unit_deny_reason', 'reason',
       'note_on_sourcing:_i_got_this_information_through_a_request_to_the_tdcj_public_information_office,_received_10/14/2022.',
       'year', 'month', 'day', 'state_arc'],
      dtype='object')

## Clean up Column Names

In [13]:
data = data.rename(columns={
    "publication": "publication",
    "author": "author",
    "date": "date",
    "reason": "reason",
    "year": "year",
    "month": "month",
    "day": "day",
    "state_arc": "state"
})

data = data.drop(columns=["unit_deny_reason", "note_on_sourcing:_i_got_this_information_through_a_request_to_the_tdcj_public_information_office,_received_10/14/2022."], errors="ignore")
data.head()

,publication,author,date,reason,year,month,day,state
0,...AND THEIR MEMORY WAS A BITTER TREE,"HOWARD, ROBERT",2016-08-19,PGS 81 & 369 SEXUALLY EXPLICIT IMAGE,2016,8,19,tx
1,"(NON)CONFORM RUSSIAN AND SOVIET ART 1958-1995,","THIEMANN, BARBARA",2012-09-10,PG 422 NUDE CHILD,2012,9,10,tx
2,SCUSE ME WHILE I KISS THE SKY,"HENDERSON, DAVID",2019-07-17,PG 294 SEXUALLY EXPLICIT IMAGE,2019,7,17,tx
3,SCUSE ME WHILE I KISS THE SKY,"HENDERSON, DAVID",2010-01-29,PAGE 9 OF PHOTO INSERT CONTAINS SEXUALLY EXPLI...,2010,1,29,tx
4,A BLACK GAZE,"CAMPT, TINA",2021-09-08,"PAGES 28, 30 & 35 CONTAIN SEXUALLY EXPLICIT IM...",2021,9,8,tx

## Reinspect the Data

In [16]:
data.shape

(9396, 8)

In [17]:
data.columns

Index(['publication', 'author', 'date', 'reason', 'year', 'month', 'day',
       'state'],
      dtype='object')

## Queries

In [20]:
# sum all rows which contain the words 'sexually explicit images'

data["reason"].str.contains("sexually explicit images", case=False, na=False).sum()

# str.contains("explicit") returns true for rows where 'explicit' appears
# case=False makes the search case-insensitive EXPLICIT vs explicit
# na=False treats missing values as false

np.int64(3222)

In [21]:
# sum all rows which contain 'nude'

data["reason"].str.contains("nude", case=False, na=False).sum()

np.int64(597)

In [33]:
# sum all rows which contain 'incest,' which is sometimes abbreviated as 'inc'

data["reason"].str.contains("inc", case=False, na=False).sum() #285

np.int64(285)

In [27]:
# sum all rows which contain 'minor'

data["reason"].str.contains("minor", case=False, na=False).sum()

np.int64(513)

In [34]:
# sum all rows which contain 'security concern'

data["reason"].str.contains("security concern", case=False, na=False).sum()

np.int64(91)

## Output Queries

In [36]:
data[data["reason"].str.contains("security concern", case=False, na=False)]

,publication,author,date,reason,year,month,day,state
102,A MESSAGE TO EVERY PRISONER IN AMERICA,"JONES, BRYACE",2022-08-30,ENTIRE BOOK CONTAINS INFORMATION DEEMED A SECU...,2022,8,30,tx
111,A PANTHER IS A BLACK CAT,"MAJOR, REGINALD",2015-01-14,ENTIRE BOOK CONTAINS INFORMATION THAT COULD CA...,2015,1,14,tx
316,ALL IN ONE COMPTIA NETWORK + EXAM N10-005,"MEYERS, MIKE",2022-03-03,ENTIRE PUBLICATION CONTAINS SECURITY CONCERNS,2022,3,3,tx
328,ALL-IN-ONE COMPTIA NETWORK + CERTIFICATION EXAM,"MEYERS, MIKE",2022-03-28,ENTIRE BOOK CONTAINS INFORMATION DEEMED A SECU...,2022,3,28,tx
406,AN AUTHENTIC GUIDE TO KALI LINUX,"BHOOPLI, SAMARAT",2020-02-03,"PAGES 10, 11, 50, 61 & 62 CONTAIN INFORMATION ...",2020,2,3,tx
...,...,...,...,...,...,...,...,...
7840,SUMMARY THE LAWS OF HUMAN NATURE,"GREENE, ROBERT",2020-01-03,ENTIRE BOOK CONTAINS MANIPULATION TECHNIQUES W...,2020,1,3,tx
8860,WHEN HELL BECOMES YOUR HOME,"COGNITO, N.",2022-03-31,ENTIRE BOOK CONTAINS SECURITY CONCERNS,2022,3,31,tx
8969,WINDOWS KERNAL PROGRAMMING,"YOSIFOVICH, PAVEL",2021-12-15,ENTIRE BOOK CONTAINS SECURITY CONCERNS,2021,12,15,tx
8990,WIRESHARK FOR SECURITY PROFESSIONALS,"BULLOCK, JESSEY",2022-07-28,ENTIRE BOOK CONTAINS INFORMATION DEEMED A SECU...,2022,7,28,tx
9023,WITHIN THE SHADOWS OF LIFE,"TABLER, RICHARD",2021-12-08,"PAGES 20, 24 & 28 CONTAIN SECURITY CONCERNS",2021,12,8,tx